language: node_js
node_js:
  - "4.1"
  - "4.0"
sudo: false
before_script:
  - npm install -g gulp
script: "gulp test"
after_success:
  # - npm install -g codeclimate-test-reporter
  # - codeclimate < coverage/lcov.info
