language: node_js
env:
  - CODECLIMATE_REPO_TOKEN=670b7232a6a5c100a0aa844f18780416e7d3df83918663fc1db0b71d02fdb986
node_js:
  - "4.1"
sudo: false
before_script:
  - npm install -g gulp
  - npm install -g codeclimate-test-reporter
script:
  - gulp test
  - gulp coverage
after_success:
  - CODECLIMATE_REPO_TOKEN=670b7232a6a5c100a0aa844f18780416e7d3df83918663fc1db0b71d02fdb986 codeclimate < coverage/lcov.info
